### ISSUE TITLE
Cannot start L-Explo

### ISSUE THREAD

**Issue by ACsillaghy** [explore-platform/l-explo#1]
When starting the app, I get an error message and cannot continue. Furthermore, on Firefox, I got a (presumably wrong) message that this was because of a missing GPU, but I think this is not the cause (as Firefox is in the list of supported browsers).
<img width="723" alt="Screenshot 2024-05-26 at 08 01 29" src="https://github.com/explore-platform/l-explo/assets/18006843/fe44c518-4675-44e8-9bab-3134c9dee422">

**Comment by Hyradus** [comment]
Hello,

the valid repository for Lunar SDAs Frontend is [THIS](https://github.com/explore-platform/l-explo_l-hex_frontend), please use it for any further issue.

Regarding your issue, it is related to the url (https://terrain.hyranet.info/data/LOLA_12/layer.json) being not reacheable.
I have replaced it with an updated and working version.

When you login in the explore platform, please verify that the L-EXPLO-L-HEX image is v7, if it is not select it from the dropdown menu and in case it is missing, just click on "update image" button.

Please, if the error persists, open a new issue on [here](https://github.com/explore-platform/l-explo_l-hex_frontend)

Giacomo
